/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ToolService } from "../tool.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ToolCreateInput } from "./ToolCreateInput";
import { Tool } from "./Tool";
import { ToolFindManyArgs } from "./ToolFindManyArgs";
import { ToolWhereUniqueInput } from "./ToolWhereUniqueInput";
import { ToolUpdateInput } from "./ToolUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ToolControllerBase {
  constructor(
    protected readonly service: ToolService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Tool })
  @nestAccessControl.UseRoles({
    resource: "Tool",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTool(@common.Body() data: ToolCreateInput): Promise<Tool> {
    return await this.service.createTool({
      data: {
        ...data,

        goal: data.goal
          ? {
              connect: data.goal,
            }
          : undefined,
      },
      select: {
        comments: true,
        createdAt: true,

        goal: {
          select: {
            id: true,
          },
        },

        id: true,
        isFree: true,
        name: true,
        updatedAt: true,
        url: true,
        validated: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Tool] })
  @ApiNestedQuery(ToolFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Tool",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async tools(@common.Req() request: Request): Promise<Tool[]> {
    const args = plainToClass(ToolFindManyArgs, request.query);
    return this.service.tools({
      ...args,
      select: {
        comments: true,
        createdAt: true,

        goal: {
          select: {
            id: true,
          },
        },

        id: true,
        isFree: true,
        name: true,
        updatedAt: true,
        url: true,
        validated: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Tool })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Tool",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async tool(
    @common.Param() params: ToolWhereUniqueInput
  ): Promise<Tool | null> {
    const result = await this.service.tool({
      where: params,
      select: {
        comments: true,
        createdAt: true,

        goal: {
          select: {
            id: true,
          },
        },

        id: true,
        isFree: true,
        name: true,
        updatedAt: true,
        url: true,
        validated: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Tool })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Tool",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTool(
    @common.Param() params: ToolWhereUniqueInput,
    @common.Body() data: ToolUpdateInput
  ): Promise<Tool | null> {
    try {
      return await this.service.updateTool({
        where: params,
        data: {
          ...data,

          goal: data.goal
            ? {
                connect: data.goal,
              }
            : undefined,
        },
        select: {
          comments: true,
          createdAt: true,

          goal: {
            select: {
              id: true,
            },
          },

          id: true,
          isFree: true,
          name: true,
          updatedAt: true,
          url: true,
          validated: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Tool })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Tool",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTool(
    @common.Param() params: ToolWhereUniqueInput
  ): Promise<Tool | null> {
    try {
      return await this.service.deleteTool({
        where: params,
        select: {
          comments: true,
          createdAt: true,

          goal: {
            select: {
              id: true,
            },
          },

          id: true,
          isFree: true,
          name: true,
          updatedAt: true,
          url: true,
          validated: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
